######################################################################################
###  ██╗░░░░░██╗░██████╗░██╗░░██╗████████╗░██╗░░░░░░░██╗░█████╗░██╗░░░░░███████╗   ###
###  ██║░░░░░██║██╔════╝░██║░░██║╚══██╔══╝░██║░░██╗░░██║██╔══██╗██║░░░░░██╔════╝   ###
###  ██║░░░░░██║██║░░██╗░███████║░░░██║░░░░╚██╗████╗██╔╝██║░░██║██║░░░░░█████╗░░   ###
###  ██║░░░░░██║██║░░╚██╗██╔══██║░░░██║░░░░░████╔═████║░██║░░██║██║░░░░░██╔══╝░░   ###
###  ███████╗██║╚██████╔╝██║░░██║░░░██║░░░░░╚██╔╝░╚██╔╝░╚█████╔╝███████╗██║░░░░░   ###
###  ╚══════╝╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░░░░╚═╝░░░╚═╝░░░╚════╝░╚══════╝╚═╝░░░░░   ###
######################################################################################
# Связь с разработчиком:
# VK - @lightwolf7
# TG - @lightwolf

#Радиус
radius: 100.0
radiusDonate: 200.0 #lwNear.donate

# Скрывать админов
hideOp: true

#Сообщения
noPlayers: "&x&F&F&E&2&5&9&lN&x&F&F&C&E&5&6&le&x&F&F&B&B&5&4&la&x&F&F&A&7&5&1&lr §7»§f Никого поблизости нет!"
nearPlayers: "&x&F&F&E&2&5&9&lN&x&F&F&C&E&5&6&le&x&F&F&B&B&5&4&la&x&F&F&A&7&5&1&lr §7»§f Игроки поблизости:"
noPermissions: "&x&F&F&E&2&5&9&lN&x&F&F&C&E&5&6&le&x&F&F&B&B&5&4&la&x&F&F&A&7&5&1&lr §7» §cВы не можете использовать эту команду!"